language: node_js
node_js:
  - 14
services: mongodb
before_script:
  - npm install
  - npm install -g serverless
deploy:
  - provider: script
  script: sls deploy
  skip_cleanup: true
  on:
    branch: main